version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydockerdb
    ports:
      - "5432:5432"
    networks:
      - ecart-network
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Added volume

  eureka-service:
    image: eureka-service:latest
    build:
      context: ./eurekaserver
    ports:
      - "8761:8761"
    networks:
      - ecart-network

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./apigateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
    environment:
      - EUREKA_SERVER=http://eureka-service:8761/eureka/
    networks:
      - ecart-network

  auth-service:
    image: auth-service:latest
    build:
      context: ./authservice
    ports:
      - "9090:9090"
    depends_on:
      - eureka-service
      - postgres
    networks:
      - ecart-network

  order-service:
    image: order-service:latest
    build:
      context: ./orderapp
    ports:
      - "8082:8082"
    depends_on:
      - eureka-service
      - postgres
    networks:
      - ecart-network

  user-service:
    image: user-service:latest
    build:
      context: ./userapp
    ports:
      - "8081:8081"
    depends_on:
      - eureka-service
      - postgres
    networks:
      - ecart-network

networks:
  ecart-network:
    driver: bridge

volumes:
  postgres-data:  # Added volume definition to store data in local of container database
    driver: local
