spring:
  application:
    name: apigateway
  cloud:
    gateway:
      httpclient:
        wiretap: true  # Enable logging for debugging
        response-timeout: 120000ms
      discovery:
        locator:
          enabled: true  # Enables automatic route creation based on Eureka service names
          secure: false  # 🔥 Forces lb://AUTHSERVICE to use HTTP
      routes:
        - id: user-service
          uri: lb://USERAPP
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: globalCB
                fallbackUri: forward:/fallback/global
        - id: order-service
          uri: lb://ORDERAPP
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: globalCB
                fallbackUri: forward:/fallback/global
        - id: auth-service
          uri: lb://AUTHSERVICE  # 🔥 Load-balanced request instead of hardcoded URL
          predicates:
            - Path=/auth/**
          filters:
            - SetRequestHeader=X-Forwarded-Proto, https
            - name: CircuitBreaker
              args:
                name: globalCB
                fallbackUri: forward:/fallback/global

eureka:
  instance:
    secure-port-enabled: false  # 🔥 Ensures Eureka does NOT register HTTPS
    non-secure-port-enabled: true
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: https://eurekaserver-4qdh.onrender.com/eureka/
    registerWithEureka: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.loadbalancer.core.LoadBalancerClient: DEBUG
    org.springframework.web.client.RestTemplate: TRACE

server:
  address: 0.0.0.0
  port: ${PORT:8443}
  keepAliveTimeout: 120000
  tomcat:
    max-connections: 200
    connection-timeout: 120000
    threads:
      max: 200
