spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        enabled: true  # Enables automatic service discovery via Eureka
        locator:
          enabled: true  # Enables automatic route creation based on Eureka service names
      routes:
        - id: user-service
          uri: lb://USERAPP
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: globalCB
                fallbackUri: forward:/fallback/global
        - id: order-service
          uri: lb://ORDERAPP
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: globalCB
                fallbackUri: forward:/fallback/global
        - id: auth-service
          uri: lb://AUTHSERVICE
#          uri: http://authservice-cnmh.onrender.com
          predicates:
            - Path=/auth/**
          filters:
#            - AuthenticationFilter # Uncomment if needed
            - name: CircuitBreaker
              args:
                name: globalCB
                fallbackUri: forward:/fallback/global
      http-client:
        response-timeout: 30000


eureka:
  client:
    serviceUrl:
      defaultZone: https://eurekaserver-pjrz.onrender.com/eureka/
    registerWithEureka: true

logging:
  file:
    name: apigateway.log
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.loadbalancer.core.LoadBalancerClient: DEBUG

server:
  port: 8080


filters:
  - name: RewritePath
    args:
      regexp: /auth/(.*)
      replacement: /$1
