spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERAPP
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: globalCB
                fallbackUri: forward:/fallback/global
        - id: order-service
          uri: lb://ORDERAPP
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: globalCB
                fallbackUri: forward:/fallback/global
        - id: auth-service
          uri: lb://AUTHSERVICE
#          uri: http://authservice-cnmh.onrender.com
          predicates:
            - Path=/auth/**
          filters:
#            - AuthenticationFilter # Uncomment if needed
            - name: CircuitBreaker
              args:
                name: globalCB
                fallbackUri: forward:/fallback/global

eureka:
  client:
    serviceUrl:
      defaultZone: https://eurekaserver-pjrz.onrender.com/eureka/
    registerWithEureka: true

logging:
  file:
    name: apigateway.log
  level:
    org.springframework.cloud.gateway: DEBUG

server:
  port: 8080


