spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERAPP
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter  # AuthenticationFilter for checking token validity
            - name: CircuitBreaker   # CircuitBreaker to handle requests if the user microservice is down
              args:
                name: globalCB
                fallbackUri: forward:/fallback/global
        - id: order-service
          uri: lb://ORDERAPP
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: globalCB
                fallbackUri: forward:/fallback/global
        - id: auth-service
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/auth/**
          filters:
#            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: globalCB
                fallbackUri: forward:/fallback/global

  # Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: https://eurekaserver-pjrz.onrender.com/eureka/
    registerWithEureka: true
logging:
  file:
    name: apigateway.log

server:
  port: 8080

