spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/therajnishraj/config_profile
          default-label: main
          clone-on-start: true  # Clone the Git repo during startup to ensure it is ready

  # Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

server:
  port: 8070
