spring:
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/therajnishraj/config_profile
          default-label: main
          clone-on-start: true  # Clone the repo during startup to ensure it's ready
