server:
  port: 9090

spring:
  application:
    name: authservice
  datasource:
    #    url: jdbc:postgresql://localhost:5432/postgres  # Database URL for Docker
    url: jdbc:postgresql://ep-frosty-cell-a8unx7sq-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
    #    username: postgres
    username: neondb_owner
    #    password: root
    password: npg_UVPp0k4HdxBq
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Eureka Client Configuration https://authservice-cig6.onrender.com
eureka:
  instance:
    preferIpAddress: false
    hostname: authservice-cig6.onrender.com
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
    metadata-map:
        secure: true  # ✅ Tells Eureka that this service uses HTTPS
  client:
    serviceUrl:
      defaultZone: https://eurekaserver-e2ow.onrender.com/eureka/ # Eureka service URL for Docker/Kubernetes
    registerWithEureka: true
logging:
  file:
    name: authservice.log


  web:
    mvc:
      cors:
        mappings:
          - path: "/auth/**"
            allowedOrigins: "*"
            allowedMethods: "GET, POST, PUT, DELETE"

management:
  endpoints:
    web:
      exposure:
        include: health, info

  instance:
    metadata-map:
      secure: true

