server:
  port: 9090

spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: authservice
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres  # Database URL for Docker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: authservice.log
