server:
  port: 9090

spring:
  application:
    name: authservice
  datasource:
    #    url: jdbc:postgresql://localhost:5432/postgres  # Database URL for Docker
    url: jdbc:postgresql://ep-frosty-cell-a8unx7sq-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
    #    username: postgres
    username: neondb_owner
    #    password: root
    password: npg_UVPp0k4HdxBq
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Eureka Client Configuration
eureka:
  instance:
    preferIpAddress: false
    hostname: userservice-lfua.onrender.com
  client:
    serviceUrl:
      defaultZone: https://eurekaserver-a3o0.onrender.com/eureka/ # Eureka service URL for Docker/Kubernetes
    registerWithEureka: true
logging:
  file:
    name: authservice.log


  web:
    mvc:
      cors:
        mappings:
          - path: "/auth/**"
            allowedOrigins: "*"
            allowedMethods: "GET, POST, PUT, DELETE"

management:
  endpoints:
    web:
      exposure:
        include: health, info


