server:
  port: 9090

spring:
  application:
    name: authservice
  datasource:
    url: jdbc:postgresql://postgres:5432/mydockerdb  # Database URL for Docker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

logging:
  file:
    name: authservice.log

