spring:
  application:
    name: orderapp

#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: CONFIGSERVER  # Refers to the Config Server service registered in Eureka

  # Database Configuration for Dockerized PostgreSQL
  datasource:
    url: jdbc:postgresql://postgres:5432/mydockerdb
    username: postgres
    password: postgres

  # JPA and Hibernate configurations
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

# Resilience4j Circuit Breaker Configurations
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50  # Percentage of failures before tripping the circuit
        wait-duration-in-open-state: 10s  # Time to wait before retrying after the circuit is open
        sliding-window-type: COUNT_BASED  # COUNT_BASED or TIME_BASED
        sliding-window-size: 10  # Number of calls to consider for the circuit
        minimum-number-of-calls: 5  # Minimum calls before evaluating the circuit breaker
    instances:
      userServiceCircuitBreaker:
        base-config: default

# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/  # Connects to Eureka server

# Optional: If you don't want Cloud Config to be enabled
spring.cloud.config.enabled: false
